//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCDSaveEdit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MCDSaveEdit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Minecraft Dungeons Save File Editor.
        /// </summary>
        public static string ABOUT_WINDOW_TITLE {
            get {
                return ResourceManager.GetString("ABOUT_WINDOW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        public static string ALL_FILES {
            get {
                return ResourceManager.GetString("ALL_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string ALL_ITEMS_FILTER {
            get {
                return ResourceManager.GetString("ALL_ITEMS_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minecraft Dungeons Save File Editor.
        /// </summary>
        public static string APPLICATION_TITLE {
            get {
                return ResourceManager.GetString("APPLICATION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor.
        /// </summary>
        public static string ARMOR_ITEMS_FILTER {
            get {
                return ResourceManager.GetString("ARMOR_ITEMS_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artifact.
        /// </summary>
        public static string ARTIFACT_ITEMS_FILTER {
            get {
                return ResourceManager.GetString("ARTIFACT_ITEMS_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string COMMON {
            get {
                return ResourceManager.GetString("COMMON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypted Character Save files.
        /// </summary>
        public static string DECRYPTED_CHARACTER_SAVE_FILES {
            get {
                return ResourceManager.GetString("DECRYPTED_CHARACTER_SAVE_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emeralds.
        /// </summary>
        public static string EMERALDS {
            get {
                return ResourceManager.GetString("EMERALDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enchanted.
        /// </summary>
        public static string ENCHANTED_ITEMS_FILTER {
            get {
                return ResourceManager.GetString("ENCHANTED_ITEMS_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypted Character Save files.
        /// </summary>
        public static string ENCRYPTED_CHARACTER_SAVE_FILES {
            get {
                return ResourceManager.GetString("ENCRYPTED_CHARACTER_SAVE_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string EXIT {
            get {
                return ResourceManager.GetString("EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to encrypt the json data..
        /// </summary>
        public static string FAILED_TO_ENCRYPT_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("FAILED_TO_ENCRYPT_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File was not in an expected format.
        /// </summary>
        public static string FAILED_TO_PARSE_FILE_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("FAILED_TO_PARSE_FILE_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content of file \&quot;{0}\&quot; could not be converted to a supported format..
        /// </summary>
        public static string FILE_DECRYPT_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("FILE_DECRYPT_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a file..
        /// </summary>
        public static string FILE_DROP_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("FILE_DROP_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file \&quot;{0}\&quot; was in an unexpected format..
        /// </summary>
        public static string FILE_IN_UNEXPECTED_FORMAT_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("FILE_IN_UNEXPECTED_FORMAT_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Files.
        /// </summary>
        public static string GAME_FILES_WINDOW_GROUPBOX_HEADER {
            get {
                return ResourceManager.GetString("GAME_FILES_WINDOW_GROUPBOX_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find game content files in the default install location. Please provide the path to the game files or launch with limited features and no game content..
        /// </summary>
        public static string GAME_FILES_WINDOW_MESSAGE {
            get {
                return ResourceManager.GetString("GAME_FILES_WINDOW_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No game content.
        /// </summary>
        public static string GAME_FILES_WINDOW_NO_CONTENT_BUTTON {
            get {
                return ResourceManager.GetString("GAME_FILES_WINDOW_NO_CONTENT_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string GAME_FILES_WINDOW_TEXTBOX_LABEL {
            get {
                return ResourceManager.GetString("GAME_FILES_WINDOW_TEXTBOX_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch using game content.
        /// </summary>
        public static string GAME_FILES_WINDOW_TITLE {
            get {
                return ResourceManager.GetString("GAME_FILES_WINDOW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items: {0}/180 Max.
        /// </summary>
        public static string ITEMS_COUNT_LABEL {
            get {
                return ResourceManager.GetString("ITEMS_COUNT_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string LEVEL {
            get {
                return ResourceManager.GetString("LEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melee.
        /// </summary>
        public static string MELEE_ITEMS_FILTER {
            get {
                return ResourceManager.GetString("MELEE_ITEMS_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MENU_ITEM_ABOUT {
            get {
                return ResourceManager.GetString("MENU_ITEM_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MENU_ITEM_FILE {
            get {
                return ResourceManager.GetString("MENU_ITEM_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get New Version.
        /// </summary>
        public static string MENU_ITEM_GET_NEW_VERSION {
            get {
                return ResourceManager.GetString("MENU_ITEM_GET_NEW_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find game content files at the given path..
        /// </summary>
        public static string NO_GAME_FILES_FOUND_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("NO_GAME_FILES_FOUND_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powerful.
        /// </summary>
        public static string POWERFUL {
            get {
                return ResourceManager.GetString("POWERFUL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranged.
        /// </summary>
        public static string RANGED_ITEMS_FILTER {
            get {
                return ResourceManager.GetString("RANGED_ITEMS_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Armor.
        /// </summary>
        public static string SELECT_ARMOR {
            get {
                return ResourceManager.GetString("SELECT_ARMOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Armor Property.
        /// </summary>
        public static string SELECT_ARMOR_PROPERTY {
            get {
                return ResourceManager.GetString("SELECT_ARMOR_PROPERTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Artifact.
        /// </summary>
        public static string SELECT_ARTIFACT {
            get {
                return ResourceManager.GetString("SELECT_ARTIFACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Enchantment.
        /// </summary>
        public static string SELECT_ENCHANTMENT {
            get {
                return ResourceManager.GetString("SELECT_ENCHANTMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Item.
        /// </summary>
        public static string SELECT_ITEM {
            get {
                return ResourceManager.GetString("SELECT_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Melee Weapon.
        /// </summary>
        public static string SELECT_MELEE_WEAPON {
            get {
                return ResourceManager.GetString("SELECT_MELEE_WEAPON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Ranged Weapon.
        /// </summary>
        public static string SELECT_RANGED_WEAPON {
            get {
                return ResourceManager.GetString("SELECT_RANGED_WEAPON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tier.
        /// </summary>
        public static string TIER {
            get {
                return ResourceManager.GetString("TIER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.
        /// </summary>
        public static string VERSION_FORMAT {
            get {
                return ResourceManager.GetString("VERSION_FORMAT", resourceCulture);
            }
        }
    }
}
